"""empty message

Revision ID: 34df9a28c1ec
Revises: bc38d4a19716
Create Date: 2021-08-19 10:34:47.797054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34df9a28c1ec'
down_revision = 'bc38d4a19716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('study_locations', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'study_locations')
    # ### end Alembic commands ###
