"""empty message

Revision ID: 47d335bedd37
Revises: de877fd3d0d7
Create Date: 2021-08-18 11:14:59.824129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d335bedd37'
down_revision = 'de877fd3d0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pronouns', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('grad_year', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('classes', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('pref_time', sa.String(length=250), nullable=True))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_column('user', 'pref_time')
    op.drop_column('user', 'classes')
    op.drop_column('user', 'grad_year')
    op.drop_column('user', 'pronouns')
    # ### end Alembic commands ###
