"""empty message

Revision ID: 637672972f10
Revises: ac1fa798d48d
Create Date: 2021-08-17 13:52:54.622717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637672972f10'
down_revision = 'ac1fa798d48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
