"""empty message

Revision ID: a4066f4c7a4b
Revises: 34df9a28c1ec
Create Date: 2021-08-19 10:40:10.999991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4066f4c7a4b'
down_revision = '34df9a28c1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_classes', sa.String(length=250), nullable=True))
    op.drop_column('user', 'classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('classes', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user', 'current_classes')
    # ### end Alembic commands ###
