"""empty message

Revision ID: bc38d4a19716
Revises: 47d335bedd37
Create Date: 2021-08-18 16:31:10.629330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc38d4a19716'
down_revision = '47d335bedd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'major')
    # ### end Alembic commands ###
